Support scalar tensor values, numpy scalars and 1-D arrays as input for metric tracking
aimhubio/aim pull request #1035
Opened 2021-11-23 16:15 UTC by AminSlk

closes #1033.

2021-11-23 16:48 UTC, gorarakelyan commented
@AminSlk thanks for the contribution ❤️  it will be reviewed by the repo maintainers as soon as possible

2021-11-25 09:13 UTC, alberttorosyan requested changes

2021-11-25 09:13 UTC, alberttorosyan commented on aim/sdk/num_utils.py
> -    if isinstance(value, float):
please keep the explicit cast to float/int. we had an [issue](https://github.com/aimhubio/aim/pull/1006) with tracking float-compatible types.

2021-11-25 09:13 UTC, alberttorosyan commented on aim/sdk/run.py
>          try:
lets split the type check into 2 parts:
1. if value is a custom object, no need to try to convert to number.
2. if `is_number(value)` returns True, try to convert to number, without catching exceptions.

2021-11-25 09:13 UTC, alberttorosyan commented on aim/sdk/num_utils.py
> +        if value.shape != (1,):
we can safely remove this check, since `ndarray.item()` will fail if it is not scalar and numpy's error message is OK.

2021-11-25 09:13 UTC, alberttorosyan commented on aim/sdk/num_utils.py
> +        return value.eval()
I guess we need to call `item()` on top, since `eval()` will return `numpy.ndarray`

2021-11-25 11:02 UTC, AminSlk commented
@alberttorosyan 
Thanks for reviewing. I've fixed the mentioned problems. And sorry for the mistakes, I'm new to the project and also to the opensource community:)

2021-11-25 11:02 UTC, AminSlk commented on aim/sdk/run.py
> +        if not is_number(value) and not isinstance(
I guess there are some tests that send `list` type to the track function. for example:
https://github.com/aimhubio/aim/blob/3bd7492f543bda4107880b779a33e4bb92606dc0/tests/api/test_run_images_api.py#L30
Should I change the tests accordingly? Or we should accept list of images?

2021-11-25 11:14 UTC, alberttorosyan commented on aim/sdk/run.py
> +        if not is_number(value) and not isinstance(
@AminSlk valid point. Completely forgot about  this. We need to allow `list` and `tuple`. Sorry for incorrect comment.

2021-11-25 11:24 UTC, AminSlk commented on aim/sdk/run.py
> +        if not is_number(value) and not isinstance(
So I'll add `list` and `tuple` back.

2021-12-13 07:47 UTC, alberttorosyan commented
Hey @AminSlk!
Sorry for late reply; I just added the required changes to Github Actions so PRs from forked repos are now triggering checks as well. May I ask you to sync with latest `main` branch so this works for you as well?

Thank you!

2021-12-13 09:22 UTC, AminSlk commented
@alberttorosyan 
Hi! Thank you for solving this issue. I've merged this branch with upstream `main`.

2021-12-13 13:12 UTC, alberttorosyan commented
@AminSlk have you enabled GH actions on forked repo? I believe you have to do that in order to have actions ran properly.

2021-12-13 15:11 UTC, AminSlk commented
I'm sorry, It wasn't enabled. I've enabled it right now.

2021-12-15 09:36 UTC, alberttorosyan commented
@AminSlk I have to ask you to sync with `main` once again 🙏
Sorry for the inconvenience.

2021-12-17 19:28 UTC, AminSlk commented
@alberttorosyan No Problem. I've synced it again. Thank you!

2021-12-20 07:08 UTC, alberttorosyan approved these changes

2021-12-20 07:08 UTC, merged

2021-12-20 07:09 UTC, alberttorosyan commented
@AminSlk I've merged this PR. Thanks a lot for the contribution and your help with tuning GH workflows 🙏

2021-12-20 07:42 UTC, AminSlk commented
@alberttorosyan Thanks a lot for helping me to contribute. I'm looking forward for more and better contributions:)

2021-12-20 16:11 UTC, SGevorg commented
Congrats on the first contribution @AminSlk - many more to come.
Sorry for the delay on our end. :)