Tune homepage texts
aimhubio/aim pull request #1161
Opened 2021-12-21 17:17 UTC by gorarakelyan

2021-12-22 07:54 UTC, roubkar approved these changes

2021-12-22 10:12 UTC, SGevorg requested changes

2021-12-22 10:12 UTC, SGevorg commented on aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.tsx
> +      'Scatter explorer helps to explore and learn relationship, correlations, and clustering effects between metrics and parameters.',
Scatters Explorer or Scatter Explorer?

2021-12-22 11:35 UTC, alberttorosyan commented on aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.tsx
> +      'Scatter explorer helps to explore and learn relationship, correlations, and clustering effects between metrics and parameters.',
maybe Scatter Plot Explorer?

2021-12-22 11:39 UTC, gorarakelyan commented on aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.tsx
> +      'Scatter explorer helps to explore and learn relationship, correlations, and clustering effects between metrics and parameters.',
@alberttorosyan too long I think

2022-01-13 15:01 UTC, gorarakelyan commented
@SGevorg is there anything else that needs to be changed?

2022-01-20 08:32 UTC, SGevorg requested changes

2022-01-20 08:32 UTC, SGevorg commented on aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.tsx
> +      'Compare 100s of metrics in a few clicks with Metrics Explorer',
on Metrics Explorer

2022-01-20 08:32 UTC, SGevorg commented on aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.tsx
> +      'Track intermediate images and search, compare them on the Images Explorer',
on Images Explorer

2022-01-20 08:32 UTC, SGevorg commented on aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.tsx
> +      'Params explorer enables a parallel coordinates view for metrics and params',
The Params Explorer

2022-01-20 08:32 UTC, SGevorg commented on aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.tsx
> +      'Explore and learn relationship, correlations, and clustering effects between metrics and parameters with Scatters Explorer',
on Scatters Explorer

2022-01-21 08:32 UTC, merged