Add data sorting(ascending/descending) by the selected properties on media pages
aimhubio/aim pull request #1183
Opened 2022-01-05 11:50 UTC by VkoHov

- Enhance `SortPopover` component
- Change sort logic in Metrics Explore and  Images Explore tables
- Add sorting control to Images Explore

2022-01-05 11:51 UTC, VkoHov commented
Resolves [#1132](https://github.com/aimhubio/aim/issues/1132)

2022-01-05 14:34 UTC, arsengit approved these changes

2022-01-05 14:34 UTC, arsengit commented on aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
> +import _ from 'lodash';
Lets use lodash-es

2022-01-05 14:34 UTC, arsengit commented on aim/web/ui/src/pages/Metrics/components/Table/SortPopover/SortPopover.scss
> +    margin-bottom: 4px;
lets replace with $space-xxxs

2022-01-05 14:34 UTC, arsengit commented on aim/web/ui/src/pages/Metrics/components/Table/SortPopover/SortPopover.tsx
> +import _ from 'lodash';
^

2022-01-07 16:35 UTC, roubkar requested changes

2022-01-07 16:35 UTC, roubkar commented on aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx
> +import _ from 'lodash';
please use `lodash-es`

2022-01-07 16:35 UTC, roubkar commented on aim/web/ui/src/utils/getSortedFields.ts
> +        sortFields.push({ ...field, order: 'asc', readonly: false } as any);
please add types for `sortField`

2022-01-10 18:15 UTC, roubkar approved these changes

2022-01-10 18:15 UTC, roubkar commented on aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
> +  analytics.trackEvent(
@rubenaprikyan check this event please

2022-01-14 11:06 UTC, rubenaprikyan approved these changes
lgtm!

2022-01-17 11:55 UTC, merged