Enhance explorer pages states
aimhubio/aim pull request #1195
Opened 2022-01-13 14:31 UTC by arsengit

2022-01-19 18:45 UTC, roubkar requested changes

2022-01-19 18:45 UTC, roubkar commented on aim/web/ui/src/components/IllustrationBlock/IllustrationBlock.tsx
> +  console.log(type, page);
please remove `console.log`

2022-01-19 18:45 UTC, roubkar commented on aim/web/ui/src/components/MediaPanel/MediaPanel.tsx
> +  console.log(mediaType, illustrationType);
please remove `console.log`

2022-01-19 18:45 UTC, roubkar commented on aim/web/ui/src/pages/Params/ParamsContainer.tsx
> +  console.log(paramsData);
please remove `console.log`

2022-02-17 19:31 UTC, Hamik25 commented on aim/web/ui/src/components/Table/Table.tsx
> +            content={illustrationConfig?.type ? null : emptyText}
I think here you don't need pass content prop.

2022-02-17 19:33 UTC, Hamik25 commented on aim/web/ui/src/pages/Bookmarks/Bookmarks.tsx
> +              content={'No Bookmarks Yet'}
I think here you don't need pass content prop.

2022-02-17 19:34 UTC, Hamik25 commented on aim/web/ui/src/pages/Tags/TagDetail.tsx
> +            <IllustrationBlock size='xLarge' content='No Runs' />
I think here you don't need pass content prop.

2022-02-18 01:06 UTC, Hamik25 approved these changes

2022-02-18 14:18 UTC, KaroMourad commented on aim/web/ui/src/services/models/explorer/createAppModel.ts
> +                // requestStatus: RequestStatusEnum.Ok,
if we need this comment please add TODO here

2022-02-18 14:19 UTC, KaroMourad commented on aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts
> +import { IImagesExploreAppConfig } from '../imagesExplore/imagesExploreAppModel';
lets change relative path to absolute

2022-02-18 15:48 UTC, KaroMourad approved these changes
lgtm

2022-02-18 16:05 UTC, merged