Tune table row states styles
aimhubio/aim pull request #1262
Opened 2022-01-27 18:06 UTC by VkoHov

- Change row color styles
- Add functionality to separate hovered and focused rows
- Change rows group header styles when it's grouped by color

2022-01-27 18:07 UTC, VkoHov commented
Resolves [#1261](https://github.com/aimhubio/aim/issues/1261)

2022-01-28 12:42 UTC, arsengit requested changes
There is a bug when you switching 8 to 24 color palette color set from grouping by color popover, the column background becoming transparent.

2022-01-28 12:42 UTC, arsengit commented on aim/web/ui/src/pages/ImagesExplore/ImagesExplore.tsx
> +                  }
You can change type here with  ! operator.

2022-02-01 10:57 UTC, arsengit approved these changes

2022-02-01 10:57 UTC, arsengit commented on aim/web/ui/src/config/table/tableConfigs.ts
> +export const tableColoredSelectionColumnWidth = 50;
@VkoHov what do you think about changing name to uppercase and separate with underlines. 
For instance COLORED_SELECTION_COLUMN_WIDTH.

2022-02-02 18:43 UTC, Hamik25 requested changes

2022-02-02 20:15 UTC, roubkar approved these changes

2022-02-02 20:22 UTC, Hamik25 approved these changes

2022-02-02 20:22 UTC, merged