[feat] Table composition advanced component/TablCard
aimhubio/aim pull request #1326
Opened 2022-02-14 07:32 UTC by rubenaprikyan

2022-02-28 16:16 UTC, arsengit requested changes

2022-02-28 16:16 UTC, arsengit commented on aim/web/ui/src/components/kit/DataList/DataList.tsx
> +      {!withoutSearchBar && (
Let's rename `withoutSearchBar` to `withSearchBar`

2022-02-28 16:18 UTC, arsengit commented on aim/web/ui/src/components/kit/Card/Card.scss
> +  width: 100%;
Also, the table columns should be without borders.

2022-03-01 11:31 UTC, arsengit approved these changes

2022-03-01 13:18 UTC, Hamik25 approved these changes

2022-03-01 14:41 UTC, rubenaprikyan reviewed
lgtm!

2022-03-01 15:32 UTC, Hamik25 approved these changes

2022-03-01 15:39 UTC, merged