Fix select form search suggestions list
aimhubio/aim pull request #1381
Opened 2022-02-22 16:37 UTC by arsengit

- Fixed select form search suggestions list

2022-02-22 18:24 UTC, arsengit commented
Resolves #1384

2022-02-22 21:11 UTC, Hamik25 commented on aim/web/ui/src/utils/app/getParamsSuggestions.ts
> +        if (data.params) {
I think here can be used an operator and one if statement with two conditions. data?.params[option] can be changed to data.params[option] if data hasn't param property or param prop is falsely value this scenario will not be executed.

2022-02-22 21:12 UTC, Hamik25 approved these changes

2022-02-24 15:38 UTC, rubenaprikyan approved these changes
lgtm!

2022-02-24 15:39 UTC, merged

2022-02-24 16:41 UTC, rubenaprikyan requested changes
Update CHANGE LOG to  **Display `None` values  in group config column.**