Add description to text explore table
aimhubio/aim pull request #1495
Opened 2022-03-10 10:41 UTC by VkoHov

2022-03-10 13:19 UTC, rubenaprikyan approved these changes
looks good

2022-03-10 19:39 UTC, Hamik25 requested changes

2022-03-10 19:39 UTC, Hamik25 commented on CHANGELOG.md
> +## 3.7.1 Mar 10, 2022
Please don't forget to change the version to 3.7.3 and date

2022-03-10 19:39 UTC, Hamik25 commented on aim/VERSION
> +3.7.1
Need change version to 3.7.3

2022-03-10 19:39 UTC, Hamik25 commented on aim/web/ui/package.json
> +  "version": "3.7.1",
Need change version to 3.7.3

2022-03-10 19:39 UTC, Hamik25 commented on aim/web/ui/src/services/models/textExplorer/textExplorerAppModel.ts
>              'HH:mm:ss · D MMM, YY',
Please move to `src/config/dates/dates.ts` this file. Then us it here.

2022-03-10 19:40 UTC, Hamik25 commented
Please also add a description for PR.

2022-03-11 15:19 UTC, Hamik25 approved these changes

2022-03-11 16:49 UTC, merged