Add ability to apply color scale on columns with numeric values
aimhubio/aim pull request #1541
Opened 2022-03-18 10:26 UTC by VkoHov

2022-03-18 10:28 UTC, VkoHov commented
Resolves [#893](https://github.com/aimhubio/aim/issues/893)

2022-03-22 07:41 UTC, Hamik25 requested changes

2022-03-22 07:41 UTC, Hamik25 commented on CHANGELOG.md
> +- Add ability to apply color scaleon columns with numeric values (VkoHov)
Please fix the typo "scaleon -> scale on"

2022-03-22 07:41 UTC, Hamik25 commented on aim/web/ui/src/components/CustomTable/TableColumn.tsx
> +                          {columnsColorScales[col.key] ? (
You can avoid double-checking here.

2022-03-22 09:11 UTC, rubenaprikyan reviewed
@VkoHov  The first thing comes to mind is, extend this functionality in other explorers, thoughts?
I thought having this in metrics explorer is valuable as well.

2022-03-22 18:08 UTC, rubenaprikyan approved these changes
lgtm

2022-03-22 18:32 UTC, merged