[fix] The image's original size cropping
aimhubio/aim pull request #1646
Opened 2022-04-10 13:21 UTC by VkoHov

Fix the rendering of images aligned by the original size

2022-04-10 13:23 UTC, VkoHov commented
Resolves [#1633](https://github.com/aimhubio/aim/issues/1633)

2022-04-11 12:51 UTC, arsengit requested changes
@VkoHov The `SPACE_BETWEEN_ITEMS` value should be the same with the gap between the items

2022-04-11 14:22 UTC, arsengit approved these changes

2022-04-12 14:40 UTC, rubenaprikyan approved these changes
lgtm!

2022-04-12 14:42 UTC, merged