[feat] requirements cleanup
aimhubio/aim pull request #1652
Opened 2022-04-13 14:56 UTC by devfox-se

2022-04-13 14:56 UTC, devfox-se commented
Covers #1650

2022-04-14 14:40 UTC, mihran113 requested changes
Left a comment there, other than that looks great 👍

2022-04-14 14:40 UTC, mihran113 commented on setup.py
> -    'aiofiles>=0.5.0',
aiofiles is required to use `FileResponse` to serve static files

2022-04-21 06:06 UTC, alberttorosyan approved these changes
lgtm

2022-04-21 06:25 UTC, alberttorosyan commented
Please rename to
`[refactor] Cleanup Python requirements` so it matches the commit message format

2022-04-28 11:31 UTC, mihran113 approved these changes

2022-04-28 11:31 UTC, merged