add sdk utils tests
aimhubio/aim pull request #1732
Opened 2022-05-08 05:03 UTC by yeghiakoronian

- aim-add-tests-to-sdk-utils
- remove a test, seems its making conflict with another test

2022-05-09 13:47 UTC, mihran113 commented
Hey @yeghiakoronian. Thanks a lot for the effort. 
Can I ask you to change the PR headline to `[feat] Add SDK utils tests` to match our guidelines?

2022-05-10 07:09 UTC, alberttorosyan requested changes
hey @yeghiakoronian ! thanks for the contribution, looks great!
left a small comment wrt typos.

2022-05-10 07:09 UTC, alberttorosyan commented on tests/sdk/test_utils.py
> +    def test_should_search_aim_repo_not_found_dot_back_sash(self, mock_os_path_exists: mock.MagicMock):
same as previous comment

2022-05-10 17:50 UTC, yeghiakoroniannexonia commented
@alberttorosyan all done

2022-05-10 17:51 UTC, yeghiakoronian commented on tests/sdk/test_utils.py
> +    def test_should_search_aim_repo_not_found_dot_back_sash(self, mock_os_path_exists: mock.MagicMock):
@alberttorosyan done

2022-05-11 21:15 UTC, alberttorosyan approved these changes

2022-05-13 07:14 UTC, alberttorosyan commented
@yeghiakoronian may I ask to also update `CHANGELOG.md`?
We need to automate the changelog generation yet, meanwhile each change is added manually.

2022-05-18 05:53 UTC, merged