[feat] Add ability to hide a batch of items in explorers
aimhubio/aim pull request #1943
Opened 2022-07-06 12:07 UTC by VkoHov

2022-07-06 12:11 UTC, VkoHov commented
Resolves [#1923](https://github.com/aimhubio/aim/issues/1923)

2022-07-11 17:13 UTC, arsengit requested changes

2022-07-11 17:13 UTC, arsengit commented on aim/web/ui/src/components/Table/HideItemsModal.tsx
> +  const actionText = hideMode ? 'hide' : 'show';
Let's move this to the bottom of the hooks

2022-07-11 17:13 UTC, arsengit commented on aim/web/ui/src/pages/Scatters/Scatters.tsx
> +                          visualizationElementType={'dots'}
Let's write enum for this

2022-07-14 14:52 UTC, arsengit approved these changes

2022-07-14 14:52 UTC, arsengit commented on aim/web/ui/src/components/Table/DeleteModal.tsx
> +  let runsDeleteRequest: any = null;
I think the abort functionality isn't needed here. Mainly we use abort on getting requests.

2022-07-18 21:00 UTC, roubkar approved these changes

2022-07-19 08:44 UTC, merged