[docs] Add table docs with hide, archive and delete functionality
aimhubio/aim pull request #2008
Opened 2022-07-28 16:54 UTC by VkoHov

2022-09-05 16:20 UTC, gorarakelyan commented on docs/source/ui/pages/table.md
> +In-progress runs can't be deleted. Wait until the process is finished or terminate the progress to be able to delete them.
terminate the process I guess

2022-09-05 16:21 UTC, gorarakelyan commented on docs/source/ui/pages/table.md
> +After clicking on the `Delete` button a popup appears where `finished` and `in-progress` runs are divided into a separate tables.
divided into separate tables

2022-09-05 16:21 UTC, gorarakelyan commented on docs/source/ui/pages/table.md
> +To undo a selected run from the selected list click on the `X` icon which appears when a row is hovered over.
To undo a selection, click on the `X` icon which appears when a row is hovered over.

2022-09-05 16:22 UTC, gorarakelyan commented on docs/source/ui/pages/table.md
> +After clicking on the `Archive/Unarchive` button a popup appears, where `unarchived` and `archived` runs are divided into a separate tables.
where `archived` and `unarchived` runs? you always mentioned archived runs first, would be better to stick to the same order

2022-09-06 13:34 UTC, SGevorg requested changes

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +The table helps to explore and compare training runs results, logged hyper-parameters, system info, etc. As well as to apply quick actions (hide, delete, archive, etc.) over a batch of selected items
The Aim Table helps to explore and compare training runs - their results, logged hyper-parameters, system info, etc. You can also use the table to hide, delete, archive and compare selected training runs in a few clicks.

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +### Delete a batch of items
Deleting selected runs

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +To delete a batch of runs select rows and click on the `Delete` button, which appears at the top of the table.
... which is located at the top of the table.

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +<img style="border-radius: 8px; border: 1px solid #E8F1FC; height: 200px" alt="Delete a batch of items" src="https://docs-blobs.s3.us-east-2.amazonaws.com/images/ui/pages/table/delete_a_batch_of_item
alt="Delete a set of selected runs"

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +In-progress runs can't be deleted. Wait until the process is finished or terminate the process to be able to delete them.
... can't be deleted. Please wait until the run is finished or terminate it to be able to delete the run.

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +To undo a selection, click on the X icon which appears when a row is hovered over.
To undo the selection, hover over the row. Then the X button will appear, press the X button.

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +<img style="border-radius: 8px; border: 1px solid #E8F1FC;" alt="Delete a batch of items popup remove run" src="https://docs-blobs.s3.us-east-2.amazonaws.com/images/ui/pages/table/delete_a_batch_of_i
alt="The popup for deleting the selected runs"

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +To archive/unarchive a batch of runs select rows and click on the `Archive/Unarchive` button, which appears at the top of the table.
...archive/unarchive a set of runs ... which is located at the top of the table...

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +### Archive/Unarchive a batch of items
Archive / Unarchive runs

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +<img style="border-radius: 8px; border: 1px solid #E8F1FC; height: 200px" alt="Archive a batch of items" src="https://docs-blobs.s3.us-east-2.amazonaws.com/images/ui/pages/table/archive_a_batch_of_it
alt="Archive the selected runs"

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +To undo a selection, click on the X icon which appears when a row is hovered over.
To undo the selection, hover over the selected row and click on the X button (appears on hover).

2022-09-06 13:34 UTC, SGevorg commented on docs/source/ui/pages/table.md
> +To hide/show a batch of items select rows and click on the `Hide/Show Lines` button, which appear at the top of the table.
... located at the top of the table.

2022-09-12 19:41 UTC, SGevorg reviewed
lgtm

2022-09-12 20:14 UTC, gorarakelyan approved these changes

2022-09-13 12:20 UTC, SGevorg approved these changes
lgtm

2022-09-13 12:21 UTC, merged