[feat] Add ability to open box in full view mode
aimhubio/aim pull request #2023
Opened 2022-08-01 15:38 UTC by arsengit

- Added BoxFullViewPopover component
- Added `weight` property for `Icon` component

2022-08-02 09:05 UTC, rubenaprikyan requested changes

2022-08-02 09:05 UTC, rubenaprikyan commented on aim/web/ui/src/modules/BaseExplorer/components/BoxFullViewPopover/BoxFullViewPopover.tsx
> +function BoxFullViewPopover({ onClose, element, sequence, groupInfo }: any) {
Could you please add `IBoxFullViewPopover` interface for props?

2022-08-02 18:20 UTC, rubenaprikyan approved these changes
Lgtm

2022-08-03 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aimhubio/aim?pullRequest=2023) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aimhubio/aim?pullRequest=2023) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Sharathmk99<br/>:x: Hamik25<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aimhubio/aim?pullRequest=2023) it.</sub>

2022-08-04 12:56 UTC, roubkar approved these changes

2022-08-04 16:00 UTC, merged