[feat] Adjust the controls section layout of the figures explorer
aimhubio/aim pull request #2150
Opened 2022-09-06 16:29 UTC by KaroMourad

- Change the controls section layout from vertical to horizontal
- Add labels to the controls

2022-09-06 16:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aimhubio/aim?pullRequest=2150) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aimhubio/aim?pullRequest=2150) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aimhubio/aim?pullRequest=2150) it.</sub>

2022-09-06 16:29 UTC, KaroMourad commented
Resolves #2149

2022-09-09 16:48 UTC, rubenaprikyan requested changes

2022-09-09 16:48 UTC, rubenaprikyan commented on CHANGELOG.md
> +- Adjust the controls section layout of the Figures explorer (KaroMourad)
Please let's make this more descriptive.

2022-09-09 16:57 UTC, rubenaprikyan approved these changes
Lgtm!

2022-09-09 17:01 UTC, merged