[feat] Add the ability to highlight syntax error on query form
aimhubio/aim pull request #2294
Opened 2022-10-24 21:32 UTC by KaroMourad

- add syntax error state on pipeline engine
- add syntax error highlighter using pipeline error state
- remove redundant `and ()` from the query, if there are no selected form data

2022-10-24 21:32 UTC, KaroMourad commented
Resolves #2265

2022-10-27 14:50 UTC, arsengit approved these changes

2022-10-28 11:22 UTC, rubenaprikyan requested changes
Lgtm!

2022-10-28 12:27 UTC, rubenaprikyan approved these changes
Lgtm!

2022-10-28 13:01 UTC, roubkar approved these changes

2022-10-28 13:03 UTC, merged