[feat] Add Acme integration
aimhubio/aim pull request #2453
Opened 2022-12-29 16:15 UTC by tmynn

Added Acme integration

2023-01-04 10:01 UTC, alberttorosyan reviewed
@tmynn, changes look good! left a couple of comments

2023-01-04 10:02 UTC, alberttorosyan commented
@tmynn please also fix the flake8 errors:
<img width="840" alt="Screen Shot 2023-01-04 at 14 01 30" src="https://user-images.githubusercontent.com/32957250/210530685-35708987-bf33-45e2-bdfc-07d53ed4895e.png">

2023-01-09 14:13 UTC, mihran113 requested changes

2023-01-09 14:13 UTC, mihran113 commented on aim/sdk/adapters/acme.py
> +    def track(self, logs, context, step=None):
For custom values tracking via maybe it's better to not force passing `context`?

2023-01-09 14:13 UTC, mihran113 commented on docs/source/quick_start/integrations.md
> +Step 2: Initialize a Aim Run via `AimCallback`, and create a logg factory using the Run.
Some typos here:
```
a Aim Run -> an Aim Run,
logg -> log
```

2023-01-09 14:13 UTC, mihran113 commented on aim/sdk/adapters/acme.py
> +class AimWritter(Logger):
I guess this should have been an `AimWriter`, right? 
Please also make sure to fix the mentions in the docs and examples as well.

2023-01-11 11:45 UTC, mihran113 approved these changes

2023-01-13 10:41 UTC, alberttorosyan approved these changes
lgtm

2023-01-13 11:02 UTC, merged