3D Geometry Explorer
aimhubio/aim pull request #2657
Opened 2023-04-17 20:32 UTC by pabhermoso

First version of a 3D Geometry Visualiser under Run Details. Please feel free to contact me and we can go over it.

I am currently struggling with the API Request under: aim/aim/web/ui/src/pages/RunDetail/GeometriesVisualizer/GeometriesVisualizer.tsx

I believe it gets stuck in "Pending".
![Screenshot 2023-04-17 at 21 31 43](https://user-images.githubusercontent.com/79603873/232603396-a9fc1df0-2fa2-4b54-abf2-c147175d004d.png)

I created a Geometry Aim Object. To run this I created a Python environment and installed aim from source and then:
_cd aim/web/ui
npm install --legacy-peer-deps
npm start_

Could you please try to run it from your side and try to identify why the API request is not being completed?

That would be super appreciated!!!

2023-04-18 13:05 UTC, pabhermoso commented
Maybe just one additional point for completeness. In the notebook insert_runs.ipynb I have an example of creating a Run with a geometry.
![Screenshot 2023-04-18 at 14 04 28](https://user-images.githubusercontent.com/79603873/232786274-5e2b8563-04ed-4d9a-bc39-0ba476f0a2d9.png)

2023-04-18 13:32 UTC, roubkar commented
Thanks for the details @pabhermoso 
We will keep you updated with the progress on fixing blobs data fetching issue.

2023-04-18 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aimhubio/aim?pullRequest=2657) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aimhubio/aim?pullRequest=2657) before we can accept your contribution.<br/><hr/>**Pablo Hermoso Moreno** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aimhubio/aim?pullRequest=2657) it.</sub>

2023-04-18 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aimhubio/aim?pullRequest=2657) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aimhubio/aim?pullRequest=2657) before we can accept your contribution.<br/><hr/>**Pablo Hermoso Moreno** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aimhubio/aim?pullRequest=2657) it.</sub>

2023-04-18 16:13 UTC, pabhermoso commented
Sorry, I just updated it now.

2023-05-01 19:52 UTC, roubkar commented
Resolves https://github.com/aimhubio/aim/issues/2644

2023-05-04 12:37 UTC, alberttorosyan requested changes
looks good! left some comments, mainly related to tracking lists of geometries vs. single geometry objects

2023-05-04 12:37 UTC, alberttorosyan commented on aim/sdk/sequences/geometry_sequence.py
> +        return geometry_typename, f'list({geometry_typename})'
Lets allow tracking of single geometry objects to improve UX when tracking and reading sequences.

2023-05-04 12:37 UTC, alberttorosyan commented on aim/web/api/runs/pydantic_models.py
> +    index: int
Remove `index`, as only single Geometry objects should be tracked.

2023-05-04 12:37 UTC, alberttorosyan commented on aim/web/api/runs/pydantic_models.py
> +GeometryList = List[GeometryInfo]
No need for `GeometryList`

2023-05-04 12:37 UTC, alberttorosyan commented on aim/web/api/runs/object_views.py
> +    model = GeometryList
`model = GeometryInfo`

2023-05-04 12:37 UTC, alberttorosyan commented on aim/sdk/objects/geometry.py
> +    # def to_numpy(self):
please remove the commented method

2023-05-04 12:37 UTC, alberttorosyan commented on aim/sdk/objects/geometry.py
> +        # if inst_has_typename(data, ['ndarray.numpy']):
please remove the commented code

2023-05-04 21:08 UTC, roubkar commented
Hey @pabhermoso, we have added some changes to this PR, which include:
- Naming refactorings - Geometry => Figure3D, Geometries => Figures3D 
- Instead of tracking a list currently, users can track a 3D figure per step
- UI improvements (styles and code cleanups)

Now these figures will be available only on the Run page, we're planning to add Explorer with a separate PR for future releases.

Thanks for your awesome work!

2023-05-04 21:10 UTC, roubkar approved these changes

2023-05-04 21:12 UTC, alberttorosyan approved these changes
Approving as all the requested changes are addressed.
@pabhermoso, thanks for the contribution! Awesome job 🚀

2023-05-04 22:17 UTC, merged

2023-05-05 12:34 UTC, pabhermoso commented
Looks awesome!!! Also, much prefer the Figure3D name. Thanks for the work putting this neatly into the UI :) @roubkar @alberttorosyan