[feat] Add ability to create reports
aimhubio/aim pull request #3189
Opened 2024-07-14 23:29 UTC by mihran113

2024-09-25 12:16 UTC, SGevorg requested changes
Left comments for the docs.

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +In `edit` mode you can create the report that you wish for and in view mode see the final result of it, the example shared above is of the `view` mode.
Create the report in  `edit` mode and view the final result in the `view` mode. The example above is on the `view` mode.

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +**```aim** sections to retrieve data from BE and visualize them. The example shown below is an overview of the `edit` mode.
Instead of BE, Aim storage.

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +To get acquainted with objects and methods to fetch and visualize data check out the sections below:
The details on objects and methods for data fetching are in the next section.

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +To retrieve data from BE the following methods of `repo` object
Aim Storage

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +To retrieve data from BE the following methods of `repo` object
Its worth mentioning that `repo` is by default available in the report context.

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +```\
Remove the backslash

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +
Its worth adding a few lines here of what these are.

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +You can easily find the report in a big pile with the search ba.
Typo: bar

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +You can easily find the report in a big pile with the search ba.
In general instead I would write:
The search bar is available so you can easily find the report you are looking for.

2024-09-25 12:16 UTC, SGevorg commented on docs/source/ui/pages/reports.md
> +You can find the `Delete` button under the options button in the upper right corner of the report card.
The `Delete` button is available with the options...

2024-09-25 14:44 UTC, alberttorosyan approved these changes
Went over backend changes and docs. BE looks good. Some minor things to be changed in the docs, already covered by Gev's feedback.

2024-09-26 14:17 UTC, mihran113 commented
> Left comments for the docs.

@SGevorg all the requested changes are addressed. Could you please have a look, and approve?

2024-09-27 11:16 UTC, SGevorg approved these changes
lgtm

2024-09-27 11:17 UTC, merged