Implement code autocomplete suggestions for AimQL search
aimhubio/aim pull request #955
Opened 2021-11-02 11:50 UTC by arsengit

2021-11-04 18:57 UTC, roubkar commented
Resolves https://github.com/aimhubio/aim/issues/372

2021-11-15 18:48 UTC, rubenaprikyan requested changes

2021-11-15 18:48 UTC, rubenaprikyan commented on aim/web/ui/src/components/kit/ExpressionAutoComplete/ExpressionAutoComplete.tsx
> +import CodeEditor from '@uiw/react-textarea-code-editor';
Add `@uiw/react-textarea-code-editor` package and it's type declarations module to `package.json` file

2021-11-27 15:57 UTC, rubenaprikyan approved these changes
looks good!
Seems can be merged and work on iterations.

2021-11-27 16:02 UTC, roubkar approved these changes

2021-11-28 20:35 UTC, merged